"""first migration

Revision ID: 661e523361a2
Revises: f9d38f9e485c
Create Date: 2022-05-12 09:08:54.569025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661e523361a2'
down_revision = 'f9d38f9e485c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
